forwarding_config updated
terraform-google-modules/terraform-google-cloud-dns pull request #27
Opened 2021-06-20 09:44 UTC by vktr-brlv

forwarding_path argument added to forwarding_config block

2021-06-21 22:55 UTC, morgante requested changes

2021-06-21 22:55 UTC, morgante commented on variables.tf
> +  type        = list(object({ ipv4_address = string, forwarding_path = string }))
Please make this `list(map(any))`.

2021-06-22 07:54 UTC, vktr-brlv commented on variables.tf
> +  type        = list(object({ ipv4_address = string, forwarding_path = string }))
done

2021-06-22 17:17 UTC, morgante approved these changes

2021-06-22 17:19 UTC, merged

2023-12-02 06:24 UTC, byronmccollum commented on variables.tf
> +  type        = list(object({ ipv4_address = string, forwarding_path = string }))
Why not `list(object({ ... }))`?